server:
  port: 8080

spring:
  application:
    name: mall-lite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_lite?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 09ijklmn
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

mall:
  order:
    rabbit:
      delay-exchange: mall.order.delay.exchange
      delay-queue: mall.order.delay.queue
      delay-routing-key: mall.order.delay.routing-key
      cancel-exchange: mall.order.cancel.exchange
      cancel-queue: mall.order.cancel.queue
      cancel-routing-key: mall.order.cancel.routing-key
      timeout-minutes: 30
